"""added address column

Revision ID: 0f47922692b4
Revises: 193c9b4ddf4a
Create Date: 2026-05-06 12:32:47.635008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f47922692b4'
down_revision: Union[str, None] = '193c9b4ddf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('provided_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'provided_address')
    # ### end Alembic commands ###
