"""add_rbac_models

Revision ID: aa117c1957f6
Revises: 0f47922692b4
Create Date: 2026-05-11 09:53:19.383291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa117c1957f6'
down_revision: Union[str, None] = '0f47922692b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ensure Enums exist
    op.execute("""
    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
            CREATE TYPE userrole AS ENUM ('CITIZEN', 'AUTHORITY');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'authoritystatus') THEN
            CREATE TYPE authoritystatus AS ENUM ('PENDING', 'RESOLVED');
        END IF;
    END $$;
    """)

    # 2. Create tables
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False), # No default yet
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    op.create_table('report_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.drop_index(op.f('ix_lifecycle_report_id'), table_name='lifecycle_events')
    
    # Add columns
    op.add_column('reports', sa.Column('authority_status', sa.String(length=50), nullable=False, server_default='PENDING'))
    op.add_column('reports', sa.Column('assigned_department_email', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('reporter_id', sa.UUID(), nullable=True))
    
    op.create_index('ix_reports_dept', 'reports', ['assigned_department_email'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')

    # 3. Cast and Set Defaults
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'CITIZEN'::userrole")
    
    op.execute("ALTER TABLE reports ALTER COLUMN authority_status DROP DEFAULT")
    op.execute("ALTER TABLE reports ALTER COLUMN authority_status TYPE authoritystatus USING authority_status::authoritystatus")
    op.execute("ALTER TABLE reports ALTER COLUMN authority_status SET DEFAULT 'PENDING'::authoritystatus")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index('ix_reports_dept', table_name='reports')
    op.drop_column('reporter_id', table_name='reports')
    op.drop_column('assigned_department_email', table_name='reports')
    op.drop_column('authority_status', table_name='reports')
    op.create_index(op.f('ix_lifecycle_report_id'), 'lifecycle_events', ['report_id'], unique=False)
    op.drop_table('report_subscribers')
    op.drop_table('users')
    # ### end Alembic commands ###
    
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS authoritystatus")
